version: '3'

services:
  webapi:
    image: webapi.netcore
    build:
      context: ./WebApi.NetCore
      dockerfile: Dockerfile
    depends_on:
      - lighthouse-1
      - lighthouse-2
    ports:
     - 5000:5000
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      
  lighthouse-1:
    image: lighthouse.netcore
    build:
      context: ./Lighthouse.NetCoreApp
      dockerfile: Dockerfile
    tty: true
    expose:
     - 4053
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_PUBLIC_HOSTNAME: lighthouse-1

  lighthouse-2:
    image: lighthouse.netcore
    tty: true
    expose:
     - "4053"
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_PUBLIC_HOSTNAME: lighthouse-2

  testagent:
    image: testagent.netcore
    build:
      context: ./TestAgent.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE

  testcoordinator:
    image: testcoordinator.netcore
    build:
      context: ./TestCoordinator.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE

  testreporter:
    image: testreporter.netcore
    build:
      context: ./TestReporter.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE

networks:
  fupp-cluster: