version: '3'

services:
  webapi:
    image: webapi.netcore
    build:
      context: ./WebApi.NetCore
      dockerfile: Dockerfile
    depends_on:
      - lighthouse-1
      - lighthouse-2
    ports:
     - 5000:5000
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_ROLE: webapi
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053
      
  lighthouse-1:
    image: lighthouse.netcore
    build:
      context: ./Lighthouse.NetCoreApp
      dockerfile: Dockerfile
    tty: true
    expose:
     - 4053
    networks:
      - fupp-cluster
    environment:
      PUBLISH_HOST: lighthouse-1
      PUBLISH_PORT: 4053
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053

  lighthouse-2:
    image: lighthouse.netcore
    tty: true
    expose:
     - "4053"
    networks:
      - fupp-cluster
    environment:
      PUBLISH_HOST: lighthouse-2
      PUBLISH_PORT: 4053
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053

  testagent:
    image: testagent.netcore
    build:
      context: ./TestAgent.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_ROLE: agent
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053

  testcoordinator:
    image: testcoordinator.netcore
    build:
      context: ./TestCoordinator.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_ROLE: coordinator
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053

  testreporter:
    image: testreporter.netcore
    build:
      context: ./TestReporter.NetCore
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - lighthouse-1
      - lighthouse-2
    networks:
      - fupp-cluster
    environment:
      ENV: NETCORE
      ENV_ROLE: reporter
      SEED_NODE_1: akka.tcp://FuppSystem@lighthouse-1:4053
      SEED_NODE_2: akka.tcp://FuppSystem@lighthouse-2:4053

networks:
  fupp-cluster: