version: '3'

services:
  webapi:
    image: webapi
    build:
      context: .\WebApi
      dockerfile: Dockerfile

  lighthouse:
    image: lighthouse
    build:
      context: .\Lighthouse
      dockerfile: Dockerfile

  testagent:
    image: testagent
    build:
      context: .\TestAgent
      dockerfile: Dockerfile

  testcoordinator:
    image: testcoordinator
    build:
      context: .\TestCoordinator
      dockerfile: Dockerfile

  testreporter:
    image: testreporter
    build:
      context: .\TestReporter
      dockerfile: Dockerfile

  console:
    image: microsoft/dotnet-framework:4.7
    command: powershell ping localhost -t