version: '3'

services:
#  webapi:
#    image: webapi
#    build:
#      context: .\WebApi
#      dockerfile: Dockerfile

  lighthouse:
    image: lighthouse.netcore
    build:
      context: ./Lighthouse.NetCoreApp
      dockerfile: Dockerfile

  testagent:
    image: testagent.netcore
    build:
      context: ./TestAgent
      dockerfile: NetCore.Dockerfile

  testcoordinator:
    image: testcoordinator.netcore
    build:
      context: ./TestCoordinator
      dockerfile: NetCore.Dockerfile

  testreporter:
    image: testreporter.netcore
    build:
      context: ./TestReporter
      dockerfile: NetCore.Dockerfile
